name: xact2
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: xact2/xact2:latest
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
    - type: bind
      source: /trzz/backup/xact2
      target: /backup
    - type: bind
      source: /trzz/certs
      target: /certs
  configurator:
    command:
    - |
      ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
      redis-socketio:
        condition: service_started
    entrypoint:
    - bash
    - -c
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SOCKETIO_PORT: "9000"
    image: xact2/xact2:latest
    networks:
      default: null
    volumes:
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
  db:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: '''$DB_PASSWORD'''
    healthcheck:
      test:
      - CMD-SHELL
      - mysqladmin ping -h localhost --password='$DB_PASSWORD'
      interval: 1s
      retries: 15
    image: mariadb:10.6
    networks:
      default: null
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  frontend:
    command:
    - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMOUT: "300"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: xact2/xact2:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8081"
      protocol: tcp
    restart: always
    volumes:
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
  queue-default:
    command:
    - bench
    - worker
    - --queue
    - default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: xact2/xact2:latest
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
    - type: bind
      source: /trzz/backup/xact2
      target: /backup
    - type: bind
      source: /trzz/certs
      target: /certs
  queue-long:
    command:
    - bench
    - worker
    - --queue
    - long
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: xact2/xact2:latest
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
    - type: bind
      source: /trzz/backup/xact2
      target: /backup
    - type: bind
      source: /trzz/certs
      target: /certs
  queue-short:
    command:
    - bench
    - worker
    - --queue
    - short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: xact2/xact2:latest
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
    - type: bind
      source: /trzz/backup/xact2
      target: /backup
    - type: bind
      source: /trzz/certs
      target: /certs
  redis-cache:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-cache-data
      target: /data
      volume: {}
  redis-queue:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-queue-data
      target: /data
      volume: {}
  redis-socketio:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-socketio-data
      target: /data
      volume: {}
  scheduler:
    command:
    - bench
    - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: xact2/xact2:latest
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
    - type: bind
      source: /trzz/backup/xact2
      target: /backup
    - type: bind
      source: /trzz/certs
      target: /certs
  websocket:
    command:
    - node
    - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: xact2/xact2:latest
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      volume: {}
    - type: volume
      source: frappe-logs
      target: /home/frappe/frappe-bench/logs
      volume: {}
networks:
  default:
    name: xact2_default
volumes:
  assets:
    name: xact2_assets
  db-data:
    name: xact2_db-data
  frappe-logs:
    name: xact2_frappe-logs
  redis-cache-data:
    name: xact2_redis-cache-data
  redis-queue-data:
    name: xact2_redis-queue-data
  redis-socketio-data:
    name: xact2_redis-socketio-data
  sites:
    name: xact2_sites
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: xact2/xact2:latest
  restart: always
  volumes:
  - sites:/home/frappe/frappe-bench/sites
  - assets:/home/frappe/frappe-bench/sites/assets
  - frappe-logs:/home/frappe/frappe-bench/logs
  - source: /trzz/backup/xact2
    target: /backup
    type: bind
  - source: /trzz/certs
    target: /certs
    type: bind
x-configurator:
  image: xact2/xact2:latest
  volumes:
  - sites:/home/frappe/frappe-bench/sites
  - assets:/home/frappe/frappe-bench/sites/assets
  - frappe-logs:/home/frappe/frappe-bench/logs
x-customizable-image:
  image: xact2/xact2:latest
  restart: always
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
